import initializeWasm, {
  coreVersion,
  traceMask,
  // Generated by `cargo xtask build-all` and intentionally not committed.
  // eslint-disable-next-line import/no-unresolved
} from '../modules/expo-local-vectorizer/artifacts/web/trace.js';
// @ts-expect-error Metro emits wasm assets as web URLs.
import wasmModule from '../modules/expo-local-vectorizer/artifacts/web/trace.wasm';
import {
  assertValidTraceMaskRequest,
  completedResponseFromUnknown,
  LocalTraceError,
  type LocalVectorizationServiceContract,
  type TraceMaskRequest,
  type TurnPolicy,
} from './LocalVectorization.types';
import { vectorizationLog } from './Logger';

const turnPolicyCode: Record<TurnPolicy, number> = {
  black: 0,
  white: 1,
  minority: 2,
};

let wasmReady: Promise<void> | undefined;

async function loadWasm(): Promise<void> {
  if (!wasmReady) {
    const startedAt = Date.now();
    vectorizationLog.info('Initializing vectorizer WASM');
    wasmReady = Promise.resolve(initializeWasm(wasmModule)).then((output) => {
      vectorizationLog.info('Vectorizer WASM initialized', {
        coreVersion: coreVersion(),
        memoryBytes: output.memory.buffer.byteLength,
        elapsedMs: Date.now() - startedAt,
      });
    });
  } else {
    vectorizationLog.debug('Reusing initialized vectorizer WASM');
  }
  return wasmReady;
}

function errorCode(error: unknown): string | undefined {
  if (typeof error === 'object' && error !== null && 'code' in error) {
    const { code } = error as { code?: unknown };
    return typeof code === 'string' ? code : undefined;
  }
  return undefined;
}

export const localVectorizationService: LocalVectorizationServiceContract = {
  async traceMask(request: TraceMaskRequest) {
    const startedAt = Date.now();
    vectorizationLog.info('Starting web mask trace', {
      width: request.width,
      height: request.height,
      maskBytes: request.pixels.byteLength,
      settings: request.settings,
    });
    try {
      assertValidTraceMaskRequest(request);
      vectorizationLog.debug('Web trace request validated');
      await loadWasm();
      const { settings } = request;
      const engineStartedAt = Date.now();
      const result: unknown = traceMask(request.pixels, request.width, request.height, {
        threshold: settings.threshold,
        sensitivity: settings.sensitivity,
        speckleMinArea: settings.speckleMinArea,
        turnPolicy: turnPolicyCode[settings.turnPolicy],
        cornerThreshold: settings.cornerThreshold,
        optimizeCurve: settings.optimizeCurve,
        maxPathCount: settings.maxPathCount,
        maxOutputBytes: settings.maxOutputBytes,
      });
      vectorizationLog.info('WASM trace engine completed', {
        elapsedMs: Date.now() - engineStartedAt,
      });
      const response = completedResponseFromUnknown(
        result,
        coreVersion(),
        request.pixels.byteLength
      );
      vectorizationLog.info('Web trace response validated', {
        diagnostics: response.diagnostics,
        warningCount: response.warnings.length,
        totalElapsedMs: Date.now() - startedAt,
      });
      return response;
    } catch (error) {
      const code = errorCode(error);
      vectorizationLog.error('Web mask trace failed', {
        code,
        width: request.width,
        height: request.height,
        maskBytes: request.pixels.byteLength,
        elapsedMs: Date.now() - startedAt,
        error,
      });
      if (
        code === 'TRACE_INVALID_DIMENSIONS' ||
        code === 'TRACE_INVALID_INPUT' ||
        code === 'TRACE_RESOURCE_LIMIT' ||
        code === 'TRACE_INVALID_OPTIONS' ||
        code === 'TRACE_ENGINE_FAILURE'
      ) {
        throw new LocalTraceError(code);
      }
      throw error;
    }
  },
};
