import initializeWasm, {
  coreVersion,
  traceMask,
  // Generated by `cargo xtask build-all` and intentionally not committed.
  // eslint-disable-next-line import/no-unresolved
} from '../modules/expo-local-vectorizer/artifacts/web/trace.js';
// @ts-expect-error Metro emits wasm assets as web URLs.
// eslint-disable-next-line import/no-unresolved
import wasmModule from '../modules/expo-local-vectorizer/artifacts/web/trace.wasm';
import {
  assertValidTraceMaskRequest,
  completedResponseFromUnknown,
  LocalTraceError,
  MAX_TRACE_WORKING_DIMENSION,
  type LocalVectorizationServiceContract,
  type TraceMaskRequest,
  type TurnPolicy,
} from './LocalVectorization.types';
import { vectorizationLog } from './Logger';

const turnPolicyCode: Record<TurnPolicy, number> = {
  black: 0,
  white: 1,
  minority: 2,
};

let wasmReady: Promise<void> | undefined;

async function loadWasm(): Promise<void> {
  if (!wasmReady) {
    const startedAt = Date.now();
    vectorizationLog.info('Initializing vectorizer WASM');
    wasmReady = Promise.resolve(initializeWasm(wasmModule)).then((output) => {
      vectorizationLog.info('Vectorizer WASM initialized', {
        coreVersion: coreVersion(),
        memoryBytes: output.memory.buffer.byteLength,
        elapsedMs: Date.now() - startedAt,
      });
    });
  } else {
    vectorizationLog.debug('Reusing initialized vectorizer WASM');
  }
  return wasmReady;
}

function errorCode(error: unknown): string | undefined {
  if (typeof error === 'object' && error !== null && 'code' in error) {
    const { code } = error as { code?: unknown };
    return typeof code === 'string' ? code : undefined;
  }
  return undefined;
}

function resizeMaskForWeb(request: TraceMaskRequest): TraceMaskRequest {
  const scale = Math.min(
    1,
    MAX_TRACE_WORKING_DIMENSION / Math.max(request.width, request.height)
  );
  if (scale === 1) {
    return request;
  }

  const width = Math.max(1, Math.round(request.width * scale));
  const height = Math.max(1, Math.round(request.height * scale));
  const pixels = new Uint8Array(width * height);
  for (let y = 0; y < height; y += 1) {
    const sourceY = Math.min(request.height - 1, Math.floor(y / scale));
    for (let x = 0; x < width; x += 1) {
      const sourceX = Math.min(request.width - 1, Math.floor(x / scale));
      pixels[y * width + x] = request.pixels[sourceY * request.width + sourceX];
    }
  }
  return { ...request, pixels, width, height };
}

export const localVectorizationService: LocalVectorizationServiceContract = {
  async traceMask(request: TraceMaskRequest) {
    const effectiveRequest = resizeMaskForWeb(request);
    const startedAt = Date.now();
    vectorizationLog.info('Starting web mask trace', {
      width: effectiveRequest.width,
      height: effectiveRequest.height,
      sourceWidth: request.width,
      sourceHeight: request.height,
      maskBytes: effectiveRequest.pixels.byteLength,
      settings: effectiveRequest.settings,
    });
    try {
      assertValidTraceMaskRequest(effectiveRequest);
      vectorizationLog.debug('Web trace request validated');
      await loadWasm();
      const { settings } = effectiveRequest;
      const engineStartedAt = Date.now();
      const result: unknown = traceMask(
        effectiveRequest.pixels,
        effectiveRequest.width,
        effectiveRequest.height,
        {
        threshold: settings.threshold,
        sensitivity: settings.sensitivity,
        speckleMinArea: settings.speckleMinArea,
        turnPolicy: turnPolicyCode[settings.turnPolicy],
        cornerThreshold: settings.cornerThreshold,
        optimizeCurve: settings.optimizeCurve,
        maxPathCount: settings.maxPathCount,
        maxOutputBytes: settings.maxOutputBytes,
        }
      );
      vectorizationLog.info('WASM trace engine completed', {
        elapsedMs: Date.now() - engineStartedAt,
      });
      const response = completedResponseFromUnknown(
        result,
        coreVersion(),
        effectiveRequest.pixels.byteLength
      );
      vectorizationLog.info('Web trace response validated', {
        diagnostics: response.diagnostics,
        warningCount: response.warnings.length,
        totalElapsedMs: Date.now() - startedAt,
      });
      return response;
    } catch (error) {
      const code = errorCode(error);
      vectorizationLog.error('Web mask trace failed', {
        code,
        width: effectiveRequest.width,
        height: effectiveRequest.height,
        maskBytes: effectiveRequest.pixels.byteLength,
        elapsedMs: Date.now() - startedAt,
        error,
      });
      if (
        code === 'TRACE_INVALID_DIMENSIONS' ||
        code === 'TRACE_INVALID_INPUT' ||
        code === 'TRACE_RESOURCE_LIMIT' ||
        code === 'TRACE_INVALID_OPTIONS' ||
        code === 'TRACE_ENGINE_FAILURE'
      ) {
        throw new LocalTraceError(code);
      }
      throw error;
    }
  },
};
